const fs = require('fs');
const path = require('path');

const pkg = require('../package.json');

const metaContent = `// This file is auto-generated by scripts/generate-meta.js
export const version = '${pkg.version}';
export const description = ${JSON.stringify(pkg.description)};
`;

fs.writeFileSync(path.resolve(__dirname, '../src/meta.ts'), metaContent);
